# -*- coding: utf-8 -*-
"""Untitled60.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AnJLqY2Nv6VckEfx0yWYrxaQRaOPRy6J
"""

import os
import zipfile
import smtplib
from flask import Flask, render_template, request
from pytube import Search, YouTube
from pydub import AudioSegment
from email.message import EmailMessage

app = Flask(__name__)

# ---------- EMAIL CONFIG ----------
EMAIL_SENDER = "tanejapiyush433@gmail.com"
EMAIL_PASSWORD = "Ptaneja@34"

# ---------- FOLDERS ----------
DOWNLOAD_FOLDER="downloads"
AUDIO_FOLDER="audio"
CUT_FOLDER="cut"
OUTPUT_FOLDER="output"

for folder in [DOWNLOAD_FOLDER,AUDIO_FOLDER,CUT_FOLDER,OUTPUT_FOLDER]:
    if not os.path.exists(folder):
        os.makedirs(folder)

# ---------- DOWNLOAD VIDEOS ----------
def download_videos(singer,count):
    search=Search(singer+" songs")
    videos=search.results[:count]
    paths=[]
    for i,video in enumerate(videos):
        yt=YouTube(video.watch_url)
        stream=yt.streams.filter(only_audio=True).first()
        file=stream.download(output_path=DOWNLOAD_FOLDER,
                             filename=f"video{i}.mp4")
        paths.append(file)
    return paths

# ---------- CONVERT TO AUDIO ----------
def convert_audio(video_paths):
    audio_paths=[]
    for i,path in enumerate(video_paths):
        audio=AudioSegment.from_file(path)
        out=f"{AUDIO_FOLDER}/audio{i}.mp3"
        audio.export(out,format="mp3")
        audio_paths.append(out)
    return audio_paths

# ---------- CUT AUDIO ----------
def cut_audio(audio_paths,duration):
    cut_paths=[]
    for i,path in enumerate(audio_paths):
        audio=AudioSegment.from_mp3(path)
        clip=audio[:duration*1000]
        out=f"{CUT_FOLDER}/cut{i}.mp3"
        clip.export(out,format="mp3")
        cut_paths.append(out)
    return cut_paths

# ---------- MERGE ----------
def merge_audio(cut_paths):
    final=AudioSegment.empty()
    for path in cut_paths:
        final+=AudioSegment.from_mp3(path)

    out=f"{OUTPUT_FOLDER}/mashup.mp3"
    final.export(out,format="mp3")
    return out

# ---------- ZIP ----------
def zip_file(file):
    zipname=file.replace(".mp3",".zip")
    with zipfile.ZipFile(zipname,'w') as z:
        z.write(file,os.path.basename(file))
    return zipname

# ---------- EMAIL ----------
def send_email(receiver,zip_path):
    msg=EmailMessage()
    msg["Subject"]="Mashup File"
    msg["From"]=EMAIL_SENDER
    msg["To"]=receiver
    msg.set_content("Your mashup is attached")

    with open(zip_path,"rb") as f:
        msg.add_attachment(f.read(),maintype="application",
                           subtype="zip",filename=os.path.basename(zip_path))

    with smtplib.SMTP_SSL("smtp.gmail.com",465) as smtp:
        smtp.login(EMAIL_SENDER,EMAIL_PASSWORD)
        smtp.send_message(msg)

# ---------- ROUTE ----------
@app.route("/",methods=["GET","POST"])
def home():
    message=""
    if request.method=="POST":
        try:
            singer=request.form["singer"]
            count=int(request.form["count"])
            duration=int(request.form["duration"])
            email=request.form["email"]

            if count<10:
                return render_template("index.html",msg="Videos must >10")

            vids=download_videos(singer,count)
            audios=convert_audio(vids)
            cuts=cut_audio(audios,duration)
            merged=merge_audio(cuts)
            zip_path=zip_file(merged)
            send_email(email,zip_path)

            message="Mashup sent to email successfully!"

        except Exception as e:
            message="Error: "+str(e)

    return render_template("index.html",msg=message)

if __name__=="__main__":
    app.run(debug=True)